env:
  global:
    - secure: "Hw0U6ZBwZkWMx6QoXC0epLPBUw1YWDwzOAfB1NV0CQMeEVkDVxjjt/kKrpg0YjrTzZo2dVmXmdCpR/it9vKX18fCqxZhyEXEy++NhaQuCmFwKGoLeeORE6iP6F1W3TZLZpoYnI6M+5SxSQwdJb9yhfxmOdPL06MaBmrGuqHvFzg="
    - secure: "XBY6qnA3evV2SZy67ZLs5iowcUe/Qfw6R2B9iv2ruMwI8S481LhKKgxOzGftlvOYSfluf1PgZh/WwyL6/OBKM/iQ6y3OHQaiIbfscszVuj1XgC8o6JaMK//rMDLBHyEyYMT9m83YWcYEzhAVZwKRYCwFh8dcfIOmxhTMHIDLJiw="
    - secure: "GE87rjqmPDq/gn662DhW73LeHbD6gLMZiTRzRQft8xIQdO+sl0/8yku+IGpelErqSpRI8c1vjlcryA6Ob1PweVaGkHn25IxPFe70UD1Xial3tXKfM/vjzyUQhtvD6CO2TdgzASe/SNJ2YZP0Diwhzs62kKsQQ9pkdSIRLSnwZ6U="
    - secure: "CN04sAdrhNOxA52hpgpw3R9YYFewM+TCz4KXe8ZlzPaWkBRfDIp3ahRHyKBEuHdtQ6No5tyMmcePKxiTgKxd0lZ2qiE3Lf+0nSdQNaJApr0Mcn4S93zh75r2+f37kcczwOnct/Y9Rf2Bb6EA1txCKfu0uAY/4Gg970z9TTeCMpc="

language: java
jdk: oraclejdk7

branches:
  only: master

before_install:
  - chmod +x gradlew
  - sudo apt-get update -qq
  - sudo apt-get install sshpass
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget http://dl.google.com/android/android-sdk_r22.6.2-linux.tgz
  - tar xzf android-sdk_r22.6.2-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - ( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | android update sdk --all --filter 3,platform-tool,tool,android-19,extra-android-support, --no-ui --force
  # The '3' in the previous command is the id of Build-Tools.
  # It is only included to get this working, and WILL BREAK
install: ./gradlew :desktop:assemble :android:assemble
script: ./gradlew :desktop:check :android:check
after_success: sshpass -p $SECRET_PASS scp -P $SECRET_PORT android/build/apk/android-debug-unaligned.apk $SECRET_USER@$SECRET_IP:www/android_latest.apk

